bwuser: 'yourusername'
bwpass: 'yourpassword'
bwsignin: 'https://schools.mybrightwheel.com/sign-in'
bwlist: 'https://schools.mybrightwheel.com/children/list'
startdate: '09/01/2023'
enddate: '09/13/2023'
